### PR TITLE
Adding Application Insights

### PR DESCRIPTION
**Pull request by lostintangent**

### CODE REVIEW

**Comment by lostintangent** [comment]
@255kb I just noticed #61, so let me know if you'd like me to add a short description to this, so that all future contributions include it. Thanks!

**Comment by 255kb** [comment]
Sure why not, maybe in another PR ?

**Comment by lostintangent** [comment]
@255kb Sounds good! As soon as you merge this PR, I'll send a new one with the short description for this and the other Visual Studio and Azure items.

**Comment by 255kb** [comment]
ok perfect :+1:

**Pull request merged**
