### PR TITLE
Added AWS's DynamoDB.

### PR DESCRIPTION
**Pull request by csterritt**
Thanks for doing this!

### CODE REVIEW

**Comment by 255kb** [comment]
Thanks for your contribution 👍 
Could you please add a link to the service to the database-hosting.md file and order by alphabetical order (both in tables of contents and service list. Thank you !

**Comment by csterritt** [comment]
Fixed alphabetizing in README.md.

**Comment by csterritt** [comment]
Caught my branch up to the current standards, I think it's ready to merge.

**Comment by 255kb** [comment]
Thanks 👍

**Pull request merged**
