### PR TITLE
Add nanobox

### PR DESCRIPTION
**Pull request by sdomino**

### CODE REVIEW

**Comment by 255kb** [comment]
Hi, thanks fr the contribution. I think that the new category could also be "Platform as a service". It seems that microplatform is not broadly used. What do you think?

**Comment by sdomino** [comment]
PaaS is probably O.K. just to put us into a category that is more recognizable. One important distinction is that nanobox doesn't provide the underlying infrastructure/hosting. You use the nanobox platform on ANY host of your choice (DO, AWS, Softlayer, etc).

I'll go ahead and update and make that change. Thanks!

**Comment by 255kb** [comment]
Ok thanks for the modification, let's see if we need a specific category in the future

**Comment by sdomino** [comment]
Ahh fair point. I hadn't considered the cost of the underlying host. Although, for any host that has a free tier, you could use this on top of that and it would technically be free, but I don't know if thats too much "workaround" to make it onto the list (maybe a "limitation"?).

**Comment by 255kb** [comment]
maybe too much workaround
also there are only two hosting provider with free tiers, AWS EC2, but only during the first year and only for t2.micro instances and Google Cloud which has only a free tier for App Engine, but only for some languages like Php. So maybe this is two "complicated" to get a completely free stack. 

I prefer keeping it outside the list for now. I will add it to the excluded list but with a special mention, so maybe we could reconsider in the future. 

What to you think?

**Comment by sdomino** [comment]
While nanobox offers a great free local development tool, I think you're probably right that, due to the nature of the production offering, it probably isn't quite the right fit for the list you're trying to build here.

Thanks!

**Pull request closed without merging**
