### PR TITLE
Travis-CI integration

### PR DESCRIPTION
**Pull request by gokaygurcan**
Hello,
Since the urls are getting more and more everyday, it'd be keep them under control and know if they are still reachable or not. https://github.com/dkhamsing/awesome_bot is the best way to do this it seems. So, I created the .travis.yml file to trigger Travis-CI to run a build and check the urls' availability. 

I hope you'll accept this PR, thanks in advance.

### CODE REVIEW

**Comment by 255kb** [comment]
Thanks I will try this !

**Comment by 255kb** [comment]
It is working really well ! thanks again :)

**Comment by gokaygurcan** [comment]
Glad to hear that! Thanks for accepting it ;)

**Comment by gokaygurcan** [comment]
By the way, I didn't want to pick a badge for you but you can do it yourself and put it to README for a better look ;) hehe

**Pull request merged**
