### PR TITLE
Added Applitools to README.md under App testing

### PR DESCRIPTION
**Pull request by zavelevsky**

### CODE REVIEW

**Comment by 255kb** [comment]
Hi thanks for the contribution, 
Do not forget to add an entry in the table of content!

**Comment by zavelevsky** [comment]
done, sorry @255kb

**Comment by 255kb** [comment]
no problem :) thanks for the update

**Comment by 255kb** [comment]
The free tier does not seem to be automatic. What does qualify a project to benefit from the free tier? 
The purpose of this list is to gather 100% free tiers for developers, without conditions. So anything limitation may disqualified the service.

**Comment by zavelevsky** [comment]
@255kb - it's not automatic but it's free for open source and also there's a free plan that's limited only in number of checkpoints - which is more than enough for an independent project.

**Comment by Panca68** [comment]
P

**Comment by Panca68** [comment]
pancaagusananda70@gmail.com

**Pull request merged**
