### PR TITLE
Checkbot patch 1

### PR DESCRIPTION
**Pull request by seanw**
Hi, I'm the creator of Checkbot. I couldn't see a category it would fit under (maybe "App testing" is close) so I created a "website testing" one. Hope you find this useful and I followed the guidelines correctly.

Thanks for the great resource!

### CODE REVIEW

**Comment by 255kb** [comment]
Thank you for the contribution 👍 
However I wonder if the category name is the best one, why not calling this category "Website audit" instead of "testing", what do you think?

**Comment by seanw** [comment]
Sounds good to me. 👍I've renamed it to this in the pull request.

**Comment by 255kb** [comment]
Thank you. That was fast! 
And congrats for this project! I saw that you are also hanging around on Indie Hackers, I started following this community.

**Comment by seanw** [comment]
Thanks! Yes, Indie Hackers is a great resource. I'll likely see you on there then. 😄

**Pull request merged**
