### PR TITLE
GearHost exceeding database size

### PR DESCRIPTION
**Pull request by tpluscode**

### CODE REVIEW

**Comment by tpluscode** [comment]
That was quick. I also wanted to add this to GearHost cloud:

*Application becomes unavailable until the limit gets reset*

How is it?

**Comment by 255kb** [comment]
For the exceeding free tier part ? What do you mean by "reset"?

**Comment by tpluscode** [comment]
60 minutes CPU time is reset every 24 hours. 256 MB of RAM usage is reset every our. bandwidth is reset every 24 hour.

And by the way, I now see that there is a limit of 250 concurrent connections:https://www.gearhost.com/documentation/difference-free-standard-reserved-plans

**Comment by 255kb** [comment]
ok, interesting, maybe you could precise the reset timeframe also, this service seems to have quite an unusual way of working :)

**Pull request merged**
